### ISSUE TITLE
Add tests to detect failure of mounting /var/lib/mysql on Windows

### ISSUE THREAD

**Issue by rfay** [drud/mariadb-local#35]
## What happened (or feature request):

When we tried to switch over to mariadb for the database in https://github.com/drud/mariadb-local/pull/30, the mounting of the database files from the host completely failed on Windows. We should be able to detect this with a decent test, even by just changing our existing tests to run with a mounted /var/lib/mysql

## Related source links or issues:

**Comment by cweagans** [comment]
We can add a test for that, but unless the test is being run on a box running Docker for Windows, we're not going to see the failure.

**Comment by rfay** [comment]
You're right... I'm silly. Closing.
