### ISSUE TITLE
Refactor tests to remove dependency on mysql client

### ISSUE THREAD

**Issue by cweagans** [drud/mariadb-local#49]
## What happened (or feature request):

We already have the mysql client installed in the container. We should use that in the tests instead of whatever mysql client is installed on the host. This way, tests dependencies are self contained.

## Related source links or issues:

**Comment by rfay** [comment]
This seems like a fine idea. I've run across this before too.

**Comment by rfay** [comment]
The only issue is it doesn't use the bind port, meaning it could have a false success if the daemon were listening only on the socket file, for example.

**Comment by rfay** [comment]
I'm going to close this for now, in general test-running machines can easily have the mysql client added to them.
